-- ====================================================================
-- Calory Calculator - Supabase Database Schema
-- Run this SQL in your Supabase Project -> SQL Editor
-- ====================================================================

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  age INTEGER,
  weight NUMERIC,
  height NUMERIC,
  goal TEXT DEFAULT 'maintain',
  avatar TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Meals Table
CREATE TABLE IF NOT EXISTS public.meals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  calories NUMERIC DEFAULT 0,
  protein NUMERIC DEFAULT 0,
  carbs NUMERIC DEFAULT 0,
  fat NUMERIC DEFAULT 0,
  fiber NUMERIC DEFAULT 0,
  sugar NUMERIC DEFAULT 0,
  sodium NUMERIC DEFAULT 0,
  serving TEXT,
  date TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Daily Goals Table
CREATE TABLE IF NOT EXISTS public.goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  calories NUMERIC DEFAULT 2000,
  protein NUMERIC DEFAULT 150,
  carbs NUMERIC DEFAULT 250,
  fat NUMERIC DEFAULT 65
);

-- 4. Create Water Intake Table
CREATE TABLE IF NOT EXISTS public.water (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  amount INTEGER DEFAULT 0,
  CONSTRAINT unique_user_date_water UNIQUE (user_id, date)
);

-- 5. Create Workouts Table
CREATE TABLE IF NOT EXISTS public.workouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  data JSONB,
  CONSTRAINT unique_user_date_workouts UNIQUE (user_id, date)
);

-- 6. Indexes for High-Performance Queries
CREATE INDEX IF NOT EXISTS idx_meals_user_date ON public.meals (user_id, date);
CREATE INDEX IF NOT EXISTS idx_water_user_date ON public.water (user_id, date);
CREATE INDEX IF NOT EXISTS idx_goals_user ON public.goals (user_id);

-- 7. Seed Default Users
-- Seed Demo Athlete
INSERT INTO public.users (id, name, email, password, role, age, weight, height, goal)
VALUES (
  1,
  'Demo Athlete',
  'demo@nutriai.com',
  '$2b$10$tZ2xN0aYp7q6FqB6nS8Ue.kG7n2rV4/VpB2T7mN8xK8vO9qP3h4Qy',
  'user',
  28,
  72,
  178,
  'maintain'
)
ON CONFLICT (email) DO NOTHING;

-- Seed Admin User (Anshuman Das)
INSERT INTO public.users (name, email, password, role, age, weight, height, goal, avatar)
VALUES (
  'Anshuman Das',
  'anshumand108@gmail.com',
  '$2b$10$tZ2xN0aYp7q6FqB6nS8Ue.kG7n2rV4/VpB2T7mN8xK8vO9qP3h4Qy',
  'admin',
  21,
  95,
  173,
  'lose',
  'A'
)
ON CONFLICT (email) DO UPDATE SET role = 'admin';

-- Seed Demo User Goals
INSERT INTO public.goals (user_id, calories, protein, carbs, fat)
VALUES (1, 2050, 150, 240, 60)
ON CONFLICT (user_id) DO NOTHING;

-- Seed Sample Meals for Demo User
INSERT INTO public.meals (user_id, name, calories, protein, carbs, fat, fiber, serving, date)
VALUES
  (1, 'Avocado Toast with Poached Eggs', 360, 18, 28, 19, 6, '1 serving', NOW()),
  (1, 'Grilled Chicken Breast & Quinoa Bowl', 520, 48, 42, 14, 5, '1 bowl', NOW()),
  (1, 'Greek Yogurt with Blueberries & Honey', 220, 20, 24, 4, 3, '1 cup', NOW())
ON CONFLICT DO NOTHING;
